AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 180

Metrics/ParameterLists:
  Max: 8

Metrics/AbcSize:
  Max: 35

Metrics/MethodLength:
  Max: 20

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
